//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/honda-obd1.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A9: return "A3 INJ_2";
		case Gpio::B14: return "B14 Output";
		case Gpio::D0: return "A1 INJ_1";
		case Gpio::D11: return "A5 INJ_3";
		case Gpio::E0: return "B11 VR1+ Discrete";
		case Gpio::E1: return "B15 max9924";
		case Gpio::E2: return "VR/Hall 1 (E2)";
		case Gpio::E3: return "VR/Hall 2 (E3)";
		case Gpio::E4: return "VR/Hall 3 (E4)";
		default: return nullptr;
	}
	return nullptr;
}
