//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/honda-obd1.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::MM100_MEGA_UAEFI_INJ1, // A1 INJ_1
	Gpio::MM100_INJ2, // A3 INJ_2
	Gpio::MM100_INJ3, // A5 INJ_3
	Gpio::B14, // B14 Output
// "A1 INJ_1",
// "A3 INJ_2",
// "A5 INJ_3",
// "B14 Output",
}
