//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/honda-obd1.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::MM100_MEGA_UAEFI_INJ1, // A1 injector out 1
	Gpio::MM100_INJ4, // A2 injector out 4
	Gpio::MM100_INJ2, // A3 injector out 2
	Gpio::MM100_INJ3, // A5 injector out 3
	Gpio::MM100_OUT_PWM2, // Fuel Pump Relay
	Gpio::MM100_INJ8, // A9 IACV output
	Gpio::MM100_INJ5, // A11 EGR solenoid Output
	Gpio::MM100_IGN8, // A12 Fan relay Output
	Gpio::MM100_INJ7, // A13 MIL output
	Gpio::MM100_OUT_PWM1, // A15 A/C clutch relay output
	Gpio::MM100_INJ6, // A17 IAB output
	Gpio::MM100_IGN7, // A21 ignition control module Output
	Gpio::MM100_LED2_GREEN, // J3_1 - LED Green
	Gpio::MM100_LED4_YELLOW, // J3_4 - LED Yellow
	Gpio::MM100_IGN5, // tach output connector 4 pin 4
	Gpio::MM100_IGN4, // Ignition Coil 4 output connector 4 pin 5
	Gpio::MM100_IGN3, // Ignition Coil 3 output connector 4 pin 6
	Gpio::MM100_IGN2, // Ignition Coil 2 output connector 4 pin 7
	Gpio::MM100_IGN1, // Ignition Coil 1 output connector J4 pin 8
	Gpio::MM100_IGN6, // A4 VTEC Solenoid output
// "A1 injector out 1",
// "A2 injector out 4",
// "A3 injector out 2",
// "A5 injector out 3",
// "Fuel Pump Relay",
// "A9 IACV output",
// "A11 EGR solenoid Output",
// "A12 Fan relay Output",
// "A13 MIL output",
// "A15 A/C clutch relay output",
// "A17 IAB output",
// "A21 ignition control module Output",
// "J3_1 - LED Green",
// "J3_4 - LED Yellow",
// "tach output connector 4 pin 4",
// "Ignition Coil 4 output connector 4 pin 5",
// "Ignition Coil 3 output connector 4 pin 6",
// "Ignition Coil 2 output connector 4 pin 7",
// "Ignition Coil 1 output connector J4 pin 8",
// "A4 VTEC Solenoid output",
}
