//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/honda-obd1.yaml
#pragma once

#define PIN_A1 MM100_MEGA_UAEFI_INJ1
#define PIN_A2 MM100_INJ4
#define PIN_A3 MM100_INJ2
#define PIN_A5 MM100_INJ3
#define PIN_A21 MM100_IGN7
#define PIN_B11 MM100_UART8_RX
#define PIN_B15 MM100_UART8_TX
#define PIN_D11 MM100_IN_TPS_ANALOG
#define PIN_D13 MM100_IN_CLT_ANALOG
#define PIN_D17 MM100_IN_MAP1_ANALOG
